[metadata]
name = lemoDB
version = 1.0.2
description = A lightweight, schema-aware, CSV-based database with auto-increment IDs
long_description = file: README.md
long_description_content_type = text/markdown
author = Richard Tekula
author_email = your.email@example.com
license = MIT
url = https://github.com/FoxerBN/lemonDB
classifiers =
    Development Status :: 4 - Beta
    Intended Audience :: Developers
    License :: OSI Approved :: MIT License
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Topic :: Database
    Topic :: Software Development :: Libraries :: Python Modules
keywords = database, csv, lightweight, schema, nosql

[options]
packages = find:
python_requires = >=3.8
install_requires =

[options.packages.find]
exclude =
    tests*
    examples*

[bdist_wheel]
universal = 0
